### ISSUE TITLE
Disabling trailing whitespace highlighting

### ISSUE THREAD

**Issue by alejoaa** [jonclayden/R-Nova#2]
Nova by default adds trailing whitespace when creating a new line below an indented line. However, lines that only contain this whitespace are highlighted. Is it possible to disable this behaviour?

Thanks

**Comment by jonclayden** [comment]
Hi Alejandro. You seem to describe two different behaviours – which one do you want to disable? And is this specific to the R extension? It sounds like it might be a general Nova issue.

**Comment by alejoaa** [comment]
Thanks Jon. That's right, the highlighting of whitespace is specific to the R extension as far as I can tell (only happens when it is active and the language is selected to R). What I'd like to disable is this highlighting and the message about the trailing whitespace. I'm including a screenshot which hopefully makes it clearer.

![Screen Shot R](https://user-images.githubusercontent.com/41101456/132775329-c1a7a0dc-ed12-4aba-8d7b-17311e97f419.png)

(The message appears when hovering over the `i` button with the mouse)

This highlighting makes the code visually convoluted unless removing that white space. I did notice that Nova has an option for removing trailing whitespace under Editor > Structure, but it'd be good to have the option to disable highlighting by the extension.

**Comment by jonclayden** [comment]
Thanks for the extra information, and the screenshot - that's really helpful. The short answer is that you should be able to disable this message on a per-project basis by creating a file in the base directory called `.lintr`, with the contents

```
linters: with_defaults(
  trailing_whitespace_linter = NULL
  )
```

To explain properly, the extension itself isn't generating this message; it comes from the [`lintr` package](https://github.com/jimhester/lintr), which is called in turn by the [`languageserver` package](https://github.com/REditorSupport/languageserver/#faq) when you have language server integration enabled within the extension. Which linters are used by the `lintr` package (and therefore reported by R-Nova) can be customised using a `.lintr` configuration file, and the syntax above disables this specific linter.

I hope that helps.

**Comment by jonclayden** [comment]
I’m assuming this is now resolved.
